package br.unb.unbiquitous.ubiquitos.authentication.messages;


/** 
 * Class used to store data generated by the first step of authentication
 * protocol. Some of this data will be used by the device in the third step,
 * for example ra and ra'. Other will be used to form the message sent to
 * middleware to execute the second step. 
 * */
public class FirstMessage {
	String hashId;
	String idEnc;
	String ra1;
	String ra2;
	String ra1Enc;
	String ra2Enc;
	String hmacM1;

	public String getHashId() {
		return hashId;
	}
	public void setHashId(String hashId) {
		this.hashId = hashId;
	}
	public String getIdEnc() {
		return idEnc;
	}
	public void setIdEnc(String idEnc) {
		this.idEnc = idEnc;
	}
	public String getRa1() {
		return ra1;
	}
	public void setRa1(String ra1) {
		this.ra1 = ra1;
	}
	public String getRa2() {
		return ra2;
	}
	public void setRa2(String ra2) {
		this.ra2 = ra2;
	}
	public String getHmacM1() {
		return hmacM1;
	}
	public void setHmacM1(String hmacM1) {
		this.hmacM1 = hmacM1;
	}
	public String getRa1Enc() {
		return ra1Enc;
	}
	public void setRa1Enc(String ra1Enc) {
		this.ra1Enc = ra1Enc;
	}
	public String getRa2Enc() {
		return ra2Enc;
	}
	public void setRa2Enc(String ra2Enc) {
		this.ra2Enc = ra2Enc;
	}
}
