package br.unb.unbiquitous.ubiquitos.authentication.messages;

/** 
 * Class used to store data generated by the second step of authentication
 * protocol. Some of this data will be used by the middleware in the fourth 
 * step, for example rb and rb'. Other will be used to form the message sent to
 * middleware to execute the third step. 
 * */
public class SecondMessage {
	String id;
	String idEnc;
	String rb1;
	String ra1Inc;
	String ra1IncEnc;
	String rb2;
	String ra2Inc;
	String ra2IncEnc;
	String rb1Enc;
	String rb2Enc;
	String hmac;
	public String getHmac() {
		return hmac;
	}
	public void setHmac(String hmac) {
		this.hmac = hmac;
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getIdEnc() {
		return idEnc;
	}
	public void setIdEnc(String idEnc) {
		this.idEnc = idEnc;
	}
	public String getRa1Inc() {
		return ra1Inc;
	}
	public void setRa1Inc(String ra1Inc) {
		this.ra1Inc = ra1Inc;
	}
	public String getRa1IncEnc() {
		return ra1IncEnc;
	}
	public void setRa1IncEnc(String ra1IncEnc) {
		this.ra1IncEnc = ra1IncEnc;
	}
	public String getRa2Inc() {
		return ra2Inc;
	}
	public void setRa2Inc(String ra2Inc) {
		this.ra2Inc = ra2Inc;
	}
	public String getRa2IncEnc() {
		return ra2IncEnc;
	}
	public void setRa2IncEnc(String ra2IncEnc) {
		this.ra2IncEnc = ra2IncEnc;
	}
	public String getRb1() {
		return rb1;
	}
	public void setRb1(String rb1) {
		this.rb1 = rb1;
	}
	public String getRb1Enc() {
		return rb1Enc;
	}
	public void setRb1Enc(String rb1Enc) {
		this.rb1Enc = rb1Enc;
	}
	public String getRb2() {
		return rb2;
	}
	public void setRb2(String rb2) {
		this.rb2 = rb2;
	}
	public String getRb2Enc() {
		return rb2Enc;
	}
	public void setRb2Enc(String rb2Enc) {
		this.rb2Enc = rb2Enc;
	}

}
