package br.unb.unbiquitous.ubiquitos.authentication.messages;

/** 
 * Class used to store data generated by the third step of authentication
 * protocol. Some of this data (chaveSessaoEncriptada and hmac) will form
 * the third message, that will be send to middleware to execute the last 
 * step.
 * */
public class ThirdMessage {
	String sessionKey;
	String sessionKeyEnc;
	String hmac;
	String id;
	
	public String getSessionKey() {
		return sessionKey;
	}
	public void setSessionKey(String sessionKey) {
		this.sessionKey = sessionKey;
	}
	public String getSessionKeyEnc() {
		return sessionKeyEnc;
	}
	public void setSessionKeyEnc(String sessionKeyEnc) {
		this.sessionKeyEnc = sessionKeyEnc;
	}
	public String getHmac() {
		return hmac;
	}
	public void setHmac(String hmac) {
		this.hmac = hmac;
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
}
